apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
- ../../base
images:
- digest: sha256:05755469537ec75fea7e517bb8bc7df0e96127f857afd7096a9c31cf40720462
  name: konachan
  newName: ghcr.io/trifoliumproj/deployment/konachan-prod
